### ISSUE TITLE
[Bug] Editing subtask does not persist on relaunch app

### ISSUE THREAD

**Issue by rancidfrog** [SecUSo/privacy-friendly-todo-list#76] opened 2020-11-11 17:47 UTC
After editing text of subtask, by longpressing a subtask selecting edit subtask then changing text and clicking okay.
Text shows changes but when you exit app and reopen it, the old text reappears.

Steps to reproduce
1. create task with subtasks,
![](https://i.imgur.com/mrvfl68.jpg)
1. Edit subtask,
![](https://i.imgur.com/mXSbj8U.jpg)
![](https://i.imgur.com/G8gyt62.jpg)
1. New subtask seems okay, yes
![](https://i.imgur.com/II2qCYx.jpg)
Great. All looks good.
But after exiting app and reopening, original subtask text displays, it changes back as new edit is not saved properly.

**Comment by 0xC0FFEEC0DE** [comment] 2024-04-14 09:42
Hello @rancidfrog , I cannot reproduce this with v2.4.2 of the app. Can you confirm that it is fixed in v2.4.2?

**Comment by 0xC0FFEEC0DE** [comment] 2024-05-01 08:33
Hello @rancidfrog ,
now I can reproduce this in v2.4.2 by completely closing the app via "App info" -> "Force stop" after renaming the subtask.
But I still cannot reproduce this in the current revision of the development branch. So the bug seems to be fixed.

**Closed by 0xC0FFEEC0DE** 2024-05-01 08:33 UTC
Labels: bug

**Comment by rancidfrog** [comment] 2024-06-03 19:53
I stopped using this app as there were no replies nor updates.
You should not expect a reply for a bug opened 4 years ago
