### ISSUE TITLE
reminder time ignores timezone

### ISSUE THREAD

**Issue by vcalv** [SecUSo/privacy-friendly-todo-list#97] opened 2023-11-20 19:37 UTC
Every time I set up an alarm for a note it uses the time I specify and converts it to another timezone (CET?)

For example, if I set the alarm for a specific local time and then I edit it, it is many hours in the future.

**Comment by 0xC0FFEEC0DE** [comment] 2024-04-14 18:48
Hello @vcalv , to reproduce this, I have to change the timezone after creating the task with reminder time:
1. create task with reminder time e.g. 8 o'clock
2. change time zone to a time zone which is +1 h in comparison with current time zone
3. when I open the task and look at the reminder time it is 9 o'clock

Is that your problem?
Without changing the timezone I cannot reproduce a changing reminder time.

**Comment by 0xC0FFEEC0DE** [comment] 2024-05-22 18:28
Hello @vcalv , now that I read your text again I'm no longer sure if you are writing about the PFA ToDo List App. The terms alarm and note do not fit. I would expect deadline / reminder and task.
Furthermore I cannot reproduce your problem. So I will close the issue.
Please re-open the issue if you have more details. Thanks.

**Closed by 0xC0FFEEC0DE** 2024-05-22 18:28 UTC
Labels: bug, invastigation required
