### ISSUE TITLE
Subtasks won't delete

### ISSUE THREAD

**Issue by kroc-ui** [SecUSo/privacy-friendly-todo-list#62] opened 2019-10-04 19:42 UTC
Moto e 2015 4g - Android 6.0
Whenever i create a subtask and then delete it, it's still there when i reopen the main task.

**Comment by Kamuno** [comment] 2019-10-06 21:35
Thank you for reporting.

Duplicate of #43

**Closed by Kamuno** 2019-10-06 21:35 UTC
Labels: bug
