### ISSUE TITLE
Notification does not trigger

### ISSUE THREAD

**Issue by Kamuno** [SecUSo/privacy-friendly-todo-list#52] opened 2018-05-07 10:52 UTC

**Comment by tareq3** [comment] 2018-06-30 10:55
yeah same here

**Comment by 0xC0FFEEC0DE** [comment] 2024-04-12 20:42
Because there are no details about this issue its hard to say what's the cause. But #115 solved an issue where the reminder service did not start. The reminder service was responsible to show the reminders. So hopefully #115 is also the fix for this issue.

**Closed by 0xC0FFEEC0DE** 2024-04-12 20:42 UTC
Labels: bug
